### ISSUE TITLE
generated query

### ISSUE THREAD

**Issue by 495256** [LinXueyuanStdio/TFLEX#2]
Could you release the generated queries? 
I attempted to use your code to generate queries for ICEWS05-15, however, it failed due to out-of-memory problem (even with 64 GB of RAM).

**Comment by LinXueyuanStdio** [comment]
Hi, 495256, thanks for following this work.

We plan to release the generated datasets when the paper is accepted. Now the datasets are under review. From the reviews, we find that the reviewers are also interested in other generated datasets, like reshaping the static complex query datasets (FB237, FB15k, NELL) to temporal ones. These datasets are still in progress.

The ICEWS14, ICEWS05-15, GDELT datasets are generated with 128 GB of RAM. However, we have implemented continue-to-run feature and optimized the usage of memory. So, just to continue running the script for more times if the memory is insufficient. It will skip the finished query types and start from the last failed one.

**Comment by LinXueyuanStdio** [comment]
Hello 495256, we have released the generated queries in [Google Drive](https://drive.google.com/drive/folders/1ddkJoUBKxgonD8rYTIL_Tb3Pei_Mtvdb?usp=sharing).
