### ISSUE TITLE
  from toolbox.data.DataSchema import DatasetCachePath, BaseData ModuleNotFoundError: No module named 'toolbox'

### ISSUE THREAD

**Issue by LittleMonster104** [LinXueyuanStdio/TFLEX#4]
Hi, when I tried to run below commend,

python train_TCQE_TFLEX.py --name="TFLEX_dim800_gamma15" --hidden_dim=800 --test_batch_size=32 --every_test_step=10000 --dataset="ICEWS14" --data_home="./data"

 I got errors:
 
 from toolbox.data.DataSchema import DatasetCachePath, BaseData
ModuleNotFoundError: No module named 'toolbox

But I have already installed toolbox using pip install toolbox, can u please help?

**Comment by Astesia12269** [comment]
me too
